# Generated by Django 2.2.13 on 2020-10-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentreply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Post Publish Status'),
        ),
        migrations.AddField(
            model_name='commentreply',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Reply Publish Status'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Commet Publish Status'),
        ),
    ]
