# Generated by Django 2.2.13 on 2020-11-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201014_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['timestamp']},
        ),
    ]
