# Generated by Django 2.2.13 on 2020-12-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='planSlotValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(default='1', max_length=2, verbose_name='Slot Number')),
                ('slot_value', models.CharField(default='50', help_text='Plan Slot Value', max_length=4, verbose_name='Slot Value')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.plan')),
            ],
        ),
    ]
