# Generated by Django 2.2.13 on 2020-09-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='next_estimated_Invoice_Bill',
        ),
    ]
