# Generated by Django 2.2.13 on 2020-12-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_planslotvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='planslotvalues',
            name='family_name',
            field=models.CharField(default='Unlimited', max_length=100, verbose_name='Family Name'),
        ),
    ]
