# Generated by Django 2.2.13 on 2020-12-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_planslotvalues_family_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planslotvalues',
            name='family_name',
        ),
    ]
