# Generated by Django 2.2.13 on 2020-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_next_estimated_invoice_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Joined'), ('Pending', 'Pending Admin Approval'), ('Active', 'Approve'), ('Decline', 'Decline')], default='Inactive', max_length=15, verbose_name='Plan Status'),
        ),
    ]
