# Generated by Django 2.2.13 on 2020-11-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20200930_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
