# Generated by Django 2.2.13 on 2020-12-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_planslotvalues_family_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='planSlotValues',
        ),
    ]
