# Generated by Django 2.2.13 on 2020-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_email_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ESIM',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ESIM/ DIGITAL SIM'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ICCID',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ICCID'),
        ),
    ]
