# Generated by Django 2.2.13 on 2020-12-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_categoryslotvalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categorySlotValues',
        ),
    ]
