# Generated by Django 2.2.13 on 2020-11-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20201114_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ESIM',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='ESIM/ DIGITAL SIM'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ICCID',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='ICCID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='area_code',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Area Code'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='device_IMEI',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='joining_condition',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Joining Condition'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mobile_carrier',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_contactNumber',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name="Subscriber's Contact Number"),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Joined'), ('Pending', 'Pending Admin Approval'), ('Active', 'Approve'), ('Ship', 'Shipment'), ('Approved', 'Activate'), ('CancelSubscription', 'Cancel Subscription'), ('7', 'Cancellation Confirm'), ('8', 'Change of Responsibility'), ('9', 'Owner Accept Change of Responsibility')], default='Inactive', max_length=40, verbose_name='Subscription Status'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subs_PIN',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='PIN Number'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subs_account',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subs_contact_switch',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Switch Contact Number'),
        ),
    ]
