# Generated by Django 2.2.13 on 2020-12-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_delete_categoryslotvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorySlotValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(default='1', max_length=2, verbose_name='Category Plan Slot Number')),
                ('slot_value', models.CharField(default='50', help_text='Plan Slot Value', max_length=4, verbose_name='Category  Plan Slot Value')),
                ('categoryplanname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.CategoryPlanName')),
            ],
        ),
    ]
