# Generated by Django 2.2.13 on 2020-12-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_categoryslotvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryplanname',
            name='average_switch',
            field=models.BooleanField(default=False, help_text='Turn on/off Average Price for a plan.', verbose_name='Average Switch'),
        ),
    ]
